// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: exchange.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateOrderRequest_OrderType int32

const (
	CreateOrderRequest_Market CreateOrderRequest_OrderType = 0
	CreateOrderRequest_Limit  CreateOrderRequest_OrderType = 1
)

// Enum value maps for CreateOrderRequest_OrderType.
var (
	CreateOrderRequest_OrderType_name = map[int32]string{
		0: "Market",
		1: "Limit",
	}
	CreateOrderRequest_OrderType_value = map[string]int32{
		"Market": 0,
		"Limit":  1,
	}
)

func (x CreateOrderRequest_OrderType) Enum() *CreateOrderRequest_OrderType {
	p := new(CreateOrderRequest_OrderType)
	*p = x
	return p
}

func (x CreateOrderRequest_OrderType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CreateOrderRequest_OrderType) Descriptor() protoreflect.EnumDescriptor {
	return file_exchange_proto_enumTypes[0].Descriptor()
}

func (CreateOrderRequest_OrderType) Type() protoreflect.EnumType {
	return &file_exchange_proto_enumTypes[0]
}

func (x CreateOrderRequest_OrderType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CreateOrderRequest_OrderType.Descriptor instead.
func (CreateOrderRequest_OrderType) EnumDescriptor() ([]byte, []int) {
	return file_exchange_proto_rawDescGZIP(), []int{4, 0}
}

type CreateOrderRequest_OrderSide int32

const (
	CreateOrderRequest_Buy  CreateOrderRequest_OrderSide = 0
	CreateOrderRequest_Sell CreateOrderRequest_OrderSide = 1
)

// Enum value maps for CreateOrderRequest_OrderSide.
var (
	CreateOrderRequest_OrderSide_name = map[int32]string{
		0: "Buy",
		1: "Sell",
	}
	CreateOrderRequest_OrderSide_value = map[string]int32{
		"Buy":  0,
		"Sell": 1,
	}
)

func (x CreateOrderRequest_OrderSide) Enum() *CreateOrderRequest_OrderSide {
	p := new(CreateOrderRequest_OrderSide)
	*p = x
	return p
}

func (x CreateOrderRequest_OrderSide) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CreateOrderRequest_OrderSide) Descriptor() protoreflect.EnumDescriptor {
	return file_exchange_proto_enumTypes[1].Descriptor()
}

func (CreateOrderRequest_OrderSide) Type() protoreflect.EnumType {
	return &file_exchange_proto_enumTypes[1]
}

func (x CreateOrderRequest_OrderSide) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CreateOrderRequest_OrderSide.Descriptor instead.
func (CreateOrderRequest_OrderSide) EnumDescriptor() ([]byte, []int) {
	return file_exchange_proto_rawDescGZIP(), []int{4, 1}
}

type ExecutionReport_OrderState int32

const (
	ExecutionReport_Booked    ExecutionReport_OrderState = 0
	ExecutionReport_Rejected  ExecutionReport_OrderState = 1
	ExecutionReport_Partial   ExecutionReport_OrderState = 2
	ExecutionReport_Filled    ExecutionReport_OrderState = 3
	ExecutionReport_Cancelled ExecutionReport_OrderState = 4
)

// Enum value maps for ExecutionReport_OrderState.
var (
	ExecutionReport_OrderState_name = map[int32]string{
		0: "Booked",
		1: "Rejected",
		2: "Partial",
		3: "Filled",
		4: "Cancelled",
	}
	ExecutionReport_OrderState_value = map[string]int32{
		"Booked":    0,
		"Rejected":  1,
		"Partial":   2,
		"Filled":    3,
		"Cancelled": 4,
	}
)

func (x ExecutionReport_OrderState) Enum() *ExecutionReport_OrderState {
	p := new(ExecutionReport_OrderState)
	*p = x
	return p
}

func (x ExecutionReport_OrderState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExecutionReport_OrderState) Descriptor() protoreflect.EnumDescriptor {
	return file_exchange_proto_enumTypes[2].Descriptor()
}

func (ExecutionReport_OrderState) Type() protoreflect.EnumType {
	return &file_exchange_proto_enumTypes[2]
}

func (x ExecutionReport_OrderState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExecutionReport_OrderState.Descriptor instead.
func (ExecutionReport_OrderState) EnumDescriptor() ([]byte, []int) {
	return file_exchange_proto_rawDescGZIP(), []int{11, 0}
}

type ExecutionReport_ReportType int32

const (
	ExecutionReport_Status ExecutionReport_ReportType = 0
	ExecutionReport_Fill   ExecutionReport_ReportType = 1
)

// Enum value maps for ExecutionReport_ReportType.
var (
	ExecutionReport_ReportType_name = map[int32]string{
		0: "Status",
		1: "Fill",
	}
	ExecutionReport_ReportType_value = map[string]int32{
		"Status": 0,
		"Fill":   1,
	}
)

func (x ExecutionReport_ReportType) Enum() *ExecutionReport_ReportType {
	p := new(ExecutionReport_ReportType)
	*p = x
	return p
}

func (x ExecutionReport_ReportType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExecutionReport_ReportType) Descriptor() protoreflect.EnumDescriptor {
	return file_exchange_proto_enumTypes[3].Descriptor()
}

func (ExecutionReport_ReportType) Type() protoreflect.EnumType {
	return &file_exchange_proto_enumTypes[3]
}

func (x ExecutionReport_ReportType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExecutionReport_ReportType.Descriptor instead.
func (ExecutionReport_ReportType) EnumDescriptor() ([]byte, []int) {
	return file_exchange_proto_rawDescGZIP(), []int{11, 1}
}

type InMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Request:
	//	*InMessage_Login
	//	*InMessage_Create
	//	*InMessage_Modify
	//	*InMessage_Cancel
	//	*InMessage_Massquote
	//	*InMessage_Secdefreq
	//	*InMessage_Download
	Request isInMessage_Request `protobuf_oneof:"request"`
}

func (x *InMessage) Reset() {
	*x = InMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_exchange_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InMessage) ProtoMessage() {}

func (x *InMessage) ProtoReflect() protoreflect.Message {
	mi := &file_exchange_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InMessage.ProtoReflect.Descriptor instead.
func (*InMessage) Descriptor() ([]byte, []int) {
	return file_exchange_proto_rawDescGZIP(), []int{0}
}

func (m *InMessage) GetRequest() isInMessage_Request {
	if m != nil {
		return m.Request
	}
	return nil
}

func (x *InMessage) GetLogin() *LoginRequest {
	if x, ok := x.GetRequest().(*InMessage_Login); ok {
		return x.Login
	}
	return nil
}

func (x *InMessage) GetCreate() *CreateOrderRequest {
	if x, ok := x.GetRequest().(*InMessage_Create); ok {
		return x.Create
	}
	return nil
}

func (x *InMessage) GetModify() *ModifyOrderRequest {
	if x, ok := x.GetRequest().(*InMessage_Modify); ok {
		return x.Modify
	}
	return nil
}

func (x *InMessage) GetCancel() *CancelOrderRequest {
	if x, ok := x.GetRequest().(*InMessage_Cancel); ok {
		return x.Cancel
	}
	return nil
}

func (x *InMessage) GetMassquote() *MassQuoteRequest {
	if x, ok := x.GetRequest().(*InMessage_Massquote); ok {
		return x.Massquote
	}
	return nil
}

func (x *InMessage) GetSecdefreq() *SecurityDefinitionRequest {
	if x, ok := x.GetRequest().(*InMessage_Secdefreq); ok {
		return x.Secdefreq
	}
	return nil
}

func (x *InMessage) GetDownload() *DownloadRequest {
	if x, ok := x.GetRequest().(*InMessage_Download); ok {
		return x.Download
	}
	return nil
}

type isInMessage_Request interface {
	isInMessage_Request()
}

type InMessage_Login struct {
	Login *LoginRequest `protobuf:"bytes,1,opt,name=login,proto3,oneof"`
}

type InMessage_Create struct {
	Create *CreateOrderRequest `protobuf:"bytes,2,opt,name=create,proto3,oneof"`
}

type InMessage_Modify struct {
	Modify *ModifyOrderRequest `protobuf:"bytes,3,opt,name=modify,proto3,oneof"`
}

type InMessage_Cancel struct {
	Cancel *CancelOrderRequest `protobuf:"bytes,4,opt,name=cancel,proto3,oneof"`
}

type InMessage_Massquote struct {
	Massquote *MassQuoteRequest `protobuf:"bytes,5,opt,name=massquote,proto3,oneof"`
}

type InMessage_Secdefreq struct {
	Secdefreq *SecurityDefinitionRequest `protobuf:"bytes,6,opt,name=secdefreq,proto3,oneof"`
}

type InMessage_Download struct {
	Download *DownloadRequest `protobuf:"bytes,7,opt,name=download,proto3,oneof"`
}

func (*InMessage_Login) isInMessage_Request() {}

func (*InMessage_Create) isInMessage_Request() {}

func (*InMessage_Modify) isInMessage_Request() {}

func (*InMessage_Cancel) isInMessage_Request() {}

func (*InMessage_Massquote) isInMessage_Request() {}

func (*InMessage_Secdefreq) isInMessage_Request() {}

func (*InMessage_Download) isInMessage_Request() {}

type OutMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Reply:
	//	*OutMessage_Login
	//	*OutMessage_Execrpt
	//	*OutMessage_Secdef
	//	*OutMessage_Reject
	Reply isOutMessage_Reply `protobuf_oneof:"reply"`
}

func (x *OutMessage) Reset() {
	*x = OutMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_exchange_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OutMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutMessage) ProtoMessage() {}

func (x *OutMessage) ProtoReflect() protoreflect.Message {
	mi := &file_exchange_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutMessage.ProtoReflect.Descriptor instead.
func (*OutMessage) Descriptor() ([]byte, []int) {
	return file_exchange_proto_rawDescGZIP(), []int{1}
}

func (m *OutMessage) GetReply() isOutMessage_Reply {
	if m != nil {
		return m.Reply
	}
	return nil
}

func (x *OutMessage) GetLogin() *LoginReply {
	if x, ok := x.GetReply().(*OutMessage_Login); ok {
		return x.Login
	}
	return nil
}

func (x *OutMessage) GetExecrpt() *ExecutionReport {
	if x, ok := x.GetReply().(*OutMessage_Execrpt); ok {
		return x.Execrpt
	}
	return nil
}

func (x *OutMessage) GetSecdef() *SecurityDefinition {
	if x, ok := x.GetReply().(*OutMessage_Secdef); ok {
		return x.Secdef
	}
	return nil
}

func (x *OutMessage) GetReject() *SessionReject {
	if x, ok := x.GetReply().(*OutMessage_Reject); ok {
		return x.Reject
	}
	return nil
}

type isOutMessage_Reply interface {
	isOutMessage_Reply()
}

type OutMessage_Login struct {
	Login *LoginReply `protobuf:"bytes,1,opt,name=login,proto3,oneof"`
}

type OutMessage_Execrpt struct {
	Execrpt *ExecutionReport `protobuf:"bytes,2,opt,name=execrpt,proto3,oneof"`
}

type OutMessage_Secdef struct {
	Secdef *SecurityDefinition `protobuf:"bytes,3,opt,name=secdef,proto3,oneof"`
}

type OutMessage_Reject struct {
	Reject *SessionReject `protobuf:"bytes,4,opt,name=reject,proto3,oneof"`
}

func (*OutMessage_Login) isOutMessage_Reply() {}

func (*OutMessage_Execrpt) isOutMessage_Reply() {}

func (*OutMessage_Secdef) isOutMessage_Reply() {}

func (*OutMessage_Reject) isOutMessage_Reply() {}

type LoginRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username"`
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password"`
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_exchange_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_exchange_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_exchange_proto_rawDescGZIP(), []int{2}
}

func (x *LoginRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error string `protobuf:"bytes,2,opt,name=error,proto3" json:"error"`
}

func (x *LoginReply) Reset() {
	*x = LoginReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_exchange_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginReply) ProtoMessage() {}

func (x *LoginReply) ProtoReflect() protoreflect.Message {
	mi := &file_exchange_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginReply.ProtoReflect.Descriptor instead.
func (*LoginReply) Descriptor() ([]byte, []int) {
	return file_exchange_proto_rawDescGZIP(), []int{3}
}

func (x *LoginReply) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type CreateOrderRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClOrdId   int32                        `protobuf:"varint,1,opt,name=clOrdId,proto3" json:"clOrdId"`
	Symbol    string                       `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol"`
	Price     float64                      `protobuf:"fixed64,3,opt,name=price,proto3" json:"price"`
	Quantity  float64                      `protobuf:"fixed64,4,opt,name=quantity,proto3" json:"quantity"`
	OrderType CreateOrderRequest_OrderType `protobuf:"varint,5,opt,name=orderType,proto3,enum=protocol.CreateOrderRequest_OrderType" json:"orderType"`
	OrderSide CreateOrderRequest_OrderSide `protobuf:"varint,6,opt,name=orderSide,proto3,enum=protocol.CreateOrderRequest_OrderSide" json:"orderSide"`
}

func (x *CreateOrderRequest) Reset() {
	*x = CreateOrderRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_exchange_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderRequest) ProtoMessage() {}

func (x *CreateOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_exchange_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderRequest.ProtoReflect.Descriptor instead.
func (*CreateOrderRequest) Descriptor() ([]byte, []int) {
	return file_exchange_proto_rawDescGZIP(), []int{4}
}

func (x *CreateOrderRequest) GetClOrdId() int32 {
	if x != nil {
		return x.ClOrdId
	}
	return 0
}

func (x *CreateOrderRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *CreateOrderRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CreateOrderRequest) GetQuantity() float64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *CreateOrderRequest) GetOrderType() CreateOrderRequest_OrderType {
	if x != nil {
		return x.OrderType
	}
	return CreateOrderRequest_Market
}

func (x *CreateOrderRequest) GetOrderSide() CreateOrderRequest_OrderSide {
	if x != nil {
		return x.OrderSide
	}
	return CreateOrderRequest_Buy
}

type ModifyOrderRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClOrdId  int32   `protobuf:"varint,1,opt,name=clOrdId,proto3" json:"clOrdId"`
	Price    float64 `protobuf:"fixed64,2,opt,name=price,proto3" json:"price"`
	Quantity float64 `protobuf:"fixed64,3,opt,name=quantity,proto3" json:"quantity"`
}

func (x *ModifyOrderRequest) Reset() {
	*x = ModifyOrderRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_exchange_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModifyOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModifyOrderRequest) ProtoMessage() {}

func (x *ModifyOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_exchange_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModifyOrderRequest.ProtoReflect.Descriptor instead.
func (*ModifyOrderRequest) Descriptor() ([]byte, []int) {
	return file_exchange_proto_rawDescGZIP(), []int{5}
}

func (x *ModifyOrderRequest) GetClOrdId() int32 {
	if x != nil {
		return x.ClOrdId
	}
	return 0
}

func (x *ModifyOrderRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *ModifyOrderRequest) GetQuantity() float64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type CancelOrderRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClOrdId int32 `protobuf:"varint,1,opt,name=clOrdId,proto3" json:"clOrdId"`
}

func (x *CancelOrderRequest) Reset() {
	*x = CancelOrderRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_exchange_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CancelOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrderRequest) ProtoMessage() {}

func (x *CancelOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_exchange_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrderRequest.ProtoReflect.Descriptor instead.
func (*CancelOrderRequest) Descriptor() ([]byte, []int) {
	return file_exchange_proto_rawDescGZIP(), []int{6}
}

func (x *CancelOrderRequest) GetClOrdId() int32 {
	if x != nil {
		return x.ClOrdId
	}
	return 0
}

type MassQuoteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Symbol      string  `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol"`
	BidPrice    float64 `protobuf:"fixed64,2,opt,name=bidPrice,proto3" json:"bidPrice"`
	BidQuantity float64 `protobuf:"fixed64,3,opt,name=bidQuantity,proto3" json:"bidQuantity"`
	AskPrice    float64 `protobuf:"fixed64,4,opt,name=askPrice,proto3" json:"askPrice"`
	AskQuantity float64 `protobuf:"fixed64,5,opt,name=askQuantity,proto3" json:"askQuantity"`
}

func (x *MassQuoteRequest) Reset() {
	*x = MassQuoteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_exchange_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MassQuoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MassQuoteRequest) ProtoMessage() {}

func (x *MassQuoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_exchange_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MassQuoteRequest.ProtoReflect.Descriptor instead.
func (*MassQuoteRequest) Descriptor() ([]byte, []int) {
	return file_exchange_proto_rawDescGZIP(), []int{7}
}

func (x *MassQuoteRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *MassQuoteRequest) GetBidPrice() float64 {
	if x != nil {
		return x.BidPrice
	}
	return 0
}

func (x *MassQuoteRequest) GetBidQuantity() float64 {
	if x != nil {
		return x.BidQuantity
	}
	return 0
}

func (x *MassQuoteRequest) GetAskPrice() float64 {
	if x != nil {
		return x.AskPrice
	}
	return 0
}

func (x *MassQuoteRequest) GetAskQuantity() float64 {
	if x != nil {
		return x.AskQuantity
	}
	return 0
}

type SecurityDefinitionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Symbol string `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol"`
}

func (x *SecurityDefinitionRequest) Reset() {
	*x = SecurityDefinitionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_exchange_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SecurityDefinitionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecurityDefinitionRequest) ProtoMessage() {}

func (x *SecurityDefinitionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_exchange_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecurityDefinitionRequest.ProtoReflect.Descriptor instead.
func (*SecurityDefinitionRequest) Descriptor() ([]byte, []int) {
	return file_exchange_proto_rawDescGZIP(), []int{8}
}

func (x *SecurityDefinitionRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

type DownloadRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DownloadRequest) Reset() {
	*x = DownloadRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_exchange_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DownloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadRequest) ProtoMessage() {}

func (x *DownloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_exchange_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadRequest.ProtoReflect.Descriptor instead.
func (*DownloadRequest) Descriptor() ([]byte, []int) {
	return file_exchange_proto_rawDescGZIP(), []int{9}
}

type SecurityDefinition struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Symbol       string `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol"`
	InstrumentID int64  `protobuf:"varint,2,opt,name=instrumentID,proto3" json:"instrumentID"`
}

func (x *SecurityDefinition) Reset() {
	*x = SecurityDefinition{}
	if protoimpl.UnsafeEnabled {
		mi := &file_exchange_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SecurityDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecurityDefinition) ProtoMessage() {}

func (x *SecurityDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_exchange_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecurityDefinition.ProtoReflect.Descriptor instead.
func (*SecurityDefinition) Descriptor() ([]byte, []int) {
	return file_exchange_proto_rawDescGZIP(), []int{10}
}

func (x *SecurityDefinition) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *SecurityDefinition) GetInstrumentID() int64 {
	if x != nil {
		return x.InstrumentID
	}
	return 0
}

type ExecutionReport struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Symbol       string                       `protobuf:"bytes,1,opt,name=Symbol,proto3" json:"Symbol"`
	ClOrdId      int32                        `protobuf:"varint,2,opt,name=clOrdId,proto3" json:"clOrdId"`
	ExOrdId      string                       `protobuf:"bytes,3,opt,name=exOrdId,proto3" json:"exOrdId"`
	OrderState   ExecutionReport_OrderState   `protobuf:"varint,4,opt,name=orderState,proto3,enum=protocol.ExecutionReport_OrderState" json:"orderState"`
	ReportType   ExecutionReport_ReportType   `protobuf:"varint,5,opt,name=reportType,proto3,enum=protocol.ExecutionReport_ReportType" json:"reportType"`
	Price        float64                      `protobuf:"fixed64,6,opt,name=price,proto3" json:"price"`
	Quantity     float64                      `protobuf:"fixed64,7,opt,name=quantity,proto3" json:"quantity"`
	Remaining    float64                      `protobuf:"fixed64,8,opt,name=remaining,proto3" json:"remaining"`
	LastPrice    float64                      `protobuf:"fixed64,9,opt,name=lastPrice,proto3" json:"lastPrice"`
	LastQuantity float64                      `protobuf:"fixed64,10,opt,name=lastQuantity,proto3" json:"lastQuantity"`
	Side         CreateOrderRequest_OrderSide `protobuf:"varint,11,opt,name=side,proto3,enum=protocol.CreateOrderRequest_OrderSide" json:"side"`
	RejectReason string                       `protobuf:"bytes,12,opt,name=rejectReason,proto3" json:"rejectReason"`
}

func (x *ExecutionReport) Reset() {
	*x = ExecutionReport{}
	if protoimpl.UnsafeEnabled {
		mi := &file_exchange_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExecutionReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionReport) ProtoMessage() {}

func (x *ExecutionReport) ProtoReflect() protoreflect.Message {
	mi := &file_exchange_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionReport.ProtoReflect.Descriptor instead.
func (*ExecutionReport) Descriptor() ([]byte, []int) {
	return file_exchange_proto_rawDescGZIP(), []int{11}
}

func (x *ExecutionReport) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *ExecutionReport) GetClOrdId() int32 {
	if x != nil {
		return x.ClOrdId
	}
	return 0
}

func (x *ExecutionReport) GetExOrdId() string {
	if x != nil {
		return x.ExOrdId
	}
	return ""
}

func (x *ExecutionReport) GetOrderState() ExecutionReport_OrderState {
	if x != nil {
		return x.OrderState
	}
	return ExecutionReport_Booked
}

func (x *ExecutionReport) GetReportType() ExecutionReport_ReportType {
	if x != nil {
		return x.ReportType
	}
	return ExecutionReport_Status
}

func (x *ExecutionReport) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *ExecutionReport) GetQuantity() float64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *ExecutionReport) GetRemaining() float64 {
	if x != nil {
		return x.Remaining
	}
	return 0
}

func (x *ExecutionReport) GetLastPrice() float64 {
	if x != nil {
		return x.LastPrice
	}
	return 0
}

func (x *ExecutionReport) GetLastQuantity() float64 {
	if x != nil {
		return x.LastQuantity
	}
	return 0
}

func (x *ExecutionReport) GetSide() CreateOrderRequest_OrderSide {
	if x != nil {
		return x.Side
	}
	return CreateOrderRequest_Buy
}

func (x *ExecutionReport) GetRejectReason() string {
	if x != nil {
		return x.RejectReason
	}
	return ""
}

type SessionReject struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error string `protobuf:"bytes,1,opt,name=error,proto3" json:"error"`
}

func (x *SessionReject) Reset() {
	*x = SessionReject{}
	if protoimpl.UnsafeEnabled {
		mi := &file_exchange_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SessionReject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionReject) ProtoMessage() {}

func (x *SessionReject) ProtoReflect() protoreflect.Message {
	mi := &file_exchange_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionReject.ProtoReflect.Descriptor instead.
func (*SessionReject) Descriptor() ([]byte, []int) {
	return file_exchange_proto_rawDescGZIP(), []int{12}
}

func (x *SessionReject) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_exchange_proto protoreflect.FileDescriptor

var file_exchange_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x65, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x22, 0xa8, 0x03, 0x0a, 0x09, 0x49,
	0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x2e, 0x0a, 0x05, 0x6c, 0x6f, 0x67, 0x69,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63,
	0x6f, 0x6c, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48,
	0x00, 0x52, 0x05, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x36, 0x0a, 0x06, 0x63, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x63, 0x6f, 0x6c, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x06, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x12, 0x36, 0x0a, 0x06, 0x6d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x4d, 0x6f, 0x64, 0x69,
	0x66, 0x79, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00,
	0x52, 0x06, 0x6d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x12, 0x36, 0x0a, 0x06, 0x63, 0x61, 0x6e, 0x63,
	0x65, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x63, 0x6f, 0x6c, 0x2e, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x06, 0x63, 0x61, 0x6e, 0x63, 0x65, 0x6c,
	0x12, 0x3a, 0x0a, 0x09, 0x6d, 0x61, 0x73, 0x73, 0x71, 0x75, 0x6f, 0x74, 0x65, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x4d,
	0x61, 0x73, 0x73, 0x51, 0x75, 0x6f, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48,
	0x00, 0x52, 0x09, 0x6d, 0x61, 0x73, 0x73, 0x71, 0x75, 0x6f, 0x74, 0x65, 0x12, 0x43, 0x0a, 0x09,
	0x73, 0x65, 0x63, 0x64, 0x65, 0x66, 0x72, 0x65, 0x71, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x23, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x53, 0x65, 0x63, 0x75, 0x72,
	0x69, 0x74, 0x79, 0x44, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x09, 0x73, 0x65, 0x63, 0x64, 0x65, 0x66, 0x72, 0x65,
	0x71, 0x12, 0x37, 0x0a, 0x08, 0x64, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x44,
	0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00,
	0x52, 0x08, 0x64, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x42, 0x09, 0x0a, 0x07, 0x72, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0xe5, 0x01, 0x0a, 0x0a, 0x4f, 0x75, 0x74, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x12, 0x2c, 0x0a, 0x05, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x4c,
	0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x48, 0x00, 0x52, 0x05, 0x6c, 0x6f, 0x67,
	0x69, 0x6e, 0x12, 0x35, 0x0a, 0x07, 0x65, 0x78, 0x65, 0x63, 0x72, 0x70, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x45,
	0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x48, 0x00,
	0x52, 0x07, 0x65, 0x78, 0x65, 0x63, 0x72, 0x70, 0x74, 0x12, 0x36, 0x0a, 0x06, 0x73, 0x65, 0x63,
	0x64, 0x65, 0x66, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x53, 0x65, 0x63, 0x75, 0x72, 0x69, 0x74, 0x79, 0x44, 0x65, 0x66,
	0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52, 0x06, 0x73, 0x65, 0x63, 0x64, 0x65,
	0x66, 0x12, 0x31, 0x0a, 0x06, 0x72, 0x65, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x53, 0x65, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x6a, 0x65, 0x63, 0x74, 0x48, 0x00, 0x52, 0x06, 0x72, 0x65,
	0x6a, 0x65, 0x63, 0x74, 0x42, 0x07, 0x0a, 0x05, 0x72, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x46, 0x0a,
	0x0c, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a,
	0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73,
	0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73,
	0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x22, 0x0a, 0x0a, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0xc8, 0x02, 0x0a, 0x12, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x18, 0x0a, 0x07, 0x63, 0x6c, 0x4f, 0x72, 0x64, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x07, 0x63, 0x6c, 0x4f, 0x72, 0x64, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x79,
	0x6d, 0x62, 0x6f, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x79, 0x6d, 0x62,
	0x6f, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x01, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x71, 0x75, 0x61, 0x6e,
	0x74, 0x69, 0x74, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x71, 0x75, 0x61, 0x6e,
	0x74, 0x69, 0x74, 0x79, 0x12, 0x44, 0x0a, 0x09, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x54, 0x79, 0x70,
	0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x26, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63,
	0x6f, 0x6c, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x52,
	0x09, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x12, 0x44, 0x0a, 0x09, 0x6f, 0x72,
	0x64, 0x65, 0x72, 0x53, 0x69, 0x64, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x26, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4f,
	0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x53, 0x69, 0x64, 0x65, 0x52, 0x09, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x53, 0x69, 0x64, 0x65,
	0x22, 0x22, 0x0a, 0x09, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0a, 0x0a,
	0x06, 0x4d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x4c, 0x69, 0x6d,
	0x69, 0x74, 0x10, 0x01, 0x22, 0x1e, 0x0a, 0x09, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x53, 0x69, 0x64,
	0x65, 0x12, 0x07, 0x0a, 0x03, 0x42, 0x75, 0x79, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x53, 0x65,
	0x6c, 0x6c, 0x10, 0x01, 0x22, 0x60, 0x0a, 0x12, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x4f, 0x72,
	0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6c,
	0x4f, 0x72, 0x64, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x63, 0x6c, 0x4f,
	0x72, 0x64, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x01, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x71, 0x75,
	0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x71, 0x75,
	0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x22, 0x2e, 0x0a, 0x12, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c,
	0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07,
	0x63, 0x6c, 0x4f, 0x72, 0x64, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x63,
	0x6c, 0x4f, 0x72, 0x64, 0x49, 0x64, 0x22, 0xa6, 0x01, 0x0a, 0x10, 0x4d, 0x61, 0x73, 0x73, 0x51,
	0x75, 0x6f, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73,
	0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x79, 0x6d,
	0x62, 0x6f, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x62, 0x69, 0x64, 0x50, 0x72, 0x69, 0x63, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x62, 0x69, 0x64, 0x50, 0x72, 0x69, 0x63, 0x65, 0x12,
	0x20, 0x0a, 0x0b, 0x62, 0x69, 0x64, 0x51, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x01, 0x52, 0x0b, 0x62, 0x69, 0x64, 0x51, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74,
	0x79, 0x12, 0x1a, 0x0a, 0x08, 0x61, 0x73, 0x6b, 0x50, 0x72, 0x69, 0x63, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x01, 0x52, 0x08, 0x61, 0x73, 0x6b, 0x50, 0x72, 0x69, 0x63, 0x65, 0x12, 0x20, 0x0a,
	0x0b, 0x61, 0x73, 0x6b, 0x51, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x0b, 0x61, 0x73, 0x6b, 0x51, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x22,
	0x33, 0x0a, 0x19, 0x53, 0x65, 0x63, 0x75, 0x72, 0x69, 0x74, 0x79, 0x44, 0x65, 0x66, 0x69, 0x6e,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06,
	0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x79,
	0x6d, 0x62, 0x6f, 0x6c, 0x22, 0x11, 0x0a, 0x0f, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x50, 0x0a, 0x12, 0x53, 0x65, 0x63, 0x75, 0x72,
	0x69, 0x74, 0x79, 0x44, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a,
	0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73,
	0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x12, 0x22, 0x0a, 0x0c, 0x69, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x6d,
	0x65, 0x6e, 0x74, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x69, 0x6e, 0x73,
	0x74, 0x72, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x22, 0xcf, 0x04, 0x0a, 0x0f, 0x45, 0x78,
	0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x16, 0x0a,
	0x06, 0x53, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x53,
	0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6c, 0x4f, 0x72, 0x64, 0x49, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x63, 0x6c, 0x4f, 0x72, 0x64, 0x49, 0x64, 0x12,
	0x18, 0x0a, 0x07, 0x65, 0x78, 0x4f, 0x72, 0x64, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x65, 0x78, 0x4f, 0x72, 0x64, 0x49, 0x64, 0x12, 0x44, 0x0a, 0x0a, 0x6f, 0x72, 0x64,
	0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x24, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x53, 0x74,
	0x61, 0x74, 0x65, 0x52, 0x0a, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12,
	0x44, 0x0a, 0x0a, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x54, 0x79, 0x70, 0x65, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x24, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x45,
	0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x2e, 0x52,
	0x65, 0x70, 0x6f, 0x72, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0a, 0x72, 0x65, 0x70, 0x6f, 0x72,
	0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x71,
	0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x07, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x71,
	0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65, 0x6d, 0x61, 0x69,
	0x6e, 0x69, 0x6e, 0x67, 0x18, 0x08, 0x20, 0x01, 0x28, 0x01, 0x52, 0x09, 0x72, 0x65, 0x6d, 0x61,
	0x69, 0x6e, 0x69, 0x6e, 0x67, 0x12, 0x1c, 0x0a, 0x09, 0x6c, 0x61, 0x73, 0x74, 0x50, 0x72, 0x69,
	0x63, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x01, 0x52, 0x09, 0x6c, 0x61, 0x73, 0x74, 0x50, 0x72,
	0x69, 0x63, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x6c, 0x61, 0x73, 0x74, 0x51, 0x75, 0x61, 0x6e, 0x74,
	0x69, 0x74, 0x79, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0c, 0x6c, 0x61, 0x73, 0x74, 0x51,
	0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x3a, 0x0a, 0x04, 0x73, 0x69, 0x64, 0x65, 0x18,
	0x0b, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x26, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c,
	0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x53, 0x69, 0x64, 0x65, 0x52, 0x04, 0x73,
	0x69, 0x64, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x72, 0x65, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x61,
	0x73, 0x6f, 0x6e, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x72, 0x65, 0x6a, 0x65, 0x63,
	0x74, 0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x22, 0x4e, 0x0a, 0x0a, 0x4f, 0x72, 0x64, 0x65, 0x72,
	0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x0a, 0x0a, 0x06, 0x42, 0x6f, 0x6f, 0x6b, 0x65, 0x64, 0x10,
	0x00, 0x12, 0x0c, 0x0a, 0x08, 0x52, 0x65, 0x6a, 0x65, 0x63, 0x74, 0x65, 0x64, 0x10, 0x01, 0x12,
	0x0b, 0x0a, 0x07, 0x50, 0x61, 0x72, 0x74, 0x69, 0x61, 0x6c, 0x10, 0x02, 0x12, 0x0a, 0x0a, 0x06,
	0x46, 0x69, 0x6c, 0x6c, 0x65, 0x64, 0x10, 0x03, 0x12, 0x0d, 0x0a, 0x09, 0x43, 0x61, 0x6e, 0x63,
	0x65, 0x6c, 0x6c, 0x65, 0x64, 0x10, 0x04, 0x22, 0x22, 0x0a, 0x0a, 0x52, 0x65, 0x70, 0x6f, 0x72,
	0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0a, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x10,
	0x00, 0x12, 0x08, 0x0a, 0x04, 0x46, 0x69, 0x6c, 0x6c, 0x10, 0x01, 0x22, 0x25, 0x0a, 0x0d, 0x53,
	0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x14, 0x0a, 0x05,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x32, 0x49, 0x0a, 0x08, 0x45, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x3d,
	0x0a, 0x0a, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x13, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x49, 0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x1a, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x4f, 0x75, 0x74,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x42, 0x0d, 0x5a,
	0x0b, 0x2e, 0x2f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_exchange_proto_rawDescOnce sync.Once
	file_exchange_proto_rawDescData = file_exchange_proto_rawDesc
)

func file_exchange_proto_rawDescGZIP() []byte {
	file_exchange_proto_rawDescOnce.Do(func() {
		file_exchange_proto_rawDescData = protoimpl.X.CompressGZIP(file_exchange_proto_rawDescData)
	})
	return file_exchange_proto_rawDescData
}

var file_exchange_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_exchange_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_exchange_proto_goTypes = []interface{}{
	(CreateOrderRequest_OrderType)(0), // 0: protocol.CreateOrderRequest.OrderType
	(CreateOrderRequest_OrderSide)(0), // 1: protocol.CreateOrderRequest.OrderSide
	(ExecutionReport_OrderState)(0),   // 2: protocol.ExecutionReport.OrderState
	(ExecutionReport_ReportType)(0),   // 3: protocol.ExecutionReport.ReportType
	(*InMessage)(nil),                 // 4: protocol.InMessage
	(*OutMessage)(nil),                // 5: protocol.OutMessage
	(*LoginRequest)(nil),              // 6: protocol.LoginRequest
	(*LoginReply)(nil),                // 7: protocol.LoginReply
	(*CreateOrderRequest)(nil),        // 8: protocol.CreateOrderRequest
	(*ModifyOrderRequest)(nil),        // 9: protocol.ModifyOrderRequest
	(*CancelOrderRequest)(nil),        // 10: protocol.CancelOrderRequest
	(*MassQuoteRequest)(nil),          // 11: protocol.MassQuoteRequest
	(*SecurityDefinitionRequest)(nil), // 12: protocol.SecurityDefinitionRequest
	(*DownloadRequest)(nil),           // 13: protocol.DownloadRequest
	(*SecurityDefinition)(nil),        // 14: protocol.SecurityDefinition
	(*ExecutionReport)(nil),           // 15: protocol.ExecutionReport
	(*SessionReject)(nil),             // 16: protocol.SessionReject
}
var file_exchange_proto_depIdxs = []int32{
	6,  // 0: protocol.InMessage.login:type_name -> protocol.LoginRequest
	8,  // 1: protocol.InMessage.create:type_name -> protocol.CreateOrderRequest
	9,  // 2: protocol.InMessage.modify:type_name -> protocol.ModifyOrderRequest
	10, // 3: protocol.InMessage.cancel:type_name -> protocol.CancelOrderRequest
	11, // 4: protocol.InMessage.massquote:type_name -> protocol.MassQuoteRequest
	12, // 5: protocol.InMessage.secdefreq:type_name -> protocol.SecurityDefinitionRequest
	13, // 6: protocol.InMessage.download:type_name -> protocol.DownloadRequest
	7,  // 7: protocol.OutMessage.login:type_name -> protocol.LoginReply
	15, // 8: protocol.OutMessage.execrpt:type_name -> protocol.ExecutionReport
	14, // 9: protocol.OutMessage.secdef:type_name -> protocol.SecurityDefinition
	16, // 10: protocol.OutMessage.reject:type_name -> protocol.SessionReject
	0,  // 11: protocol.CreateOrderRequest.orderType:type_name -> protocol.CreateOrderRequest.OrderType
	1,  // 12: protocol.CreateOrderRequest.orderSide:type_name -> protocol.CreateOrderRequest.OrderSide
	2,  // 13: protocol.ExecutionReport.orderState:type_name -> protocol.ExecutionReport.OrderState
	3,  // 14: protocol.ExecutionReport.reportType:type_name -> protocol.ExecutionReport.ReportType
	1,  // 15: protocol.ExecutionReport.side:type_name -> protocol.CreateOrderRequest.OrderSide
	4,  // 16: protocol.Exchange.Connection:input_type -> protocol.InMessage
	5,  // 17: protocol.Exchange.Connection:output_type -> protocol.OutMessage
	17, // [17:18] is the sub-list for method output_type
	16, // [16:17] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_exchange_proto_init() }
func file_exchange_proto_init() {
	if File_exchange_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_exchange_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_exchange_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OutMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_exchange_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_exchange_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_exchange_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateOrderRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_exchange_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModifyOrderRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_exchange_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CancelOrderRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_exchange_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MassQuoteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_exchange_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SecurityDefinitionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_exchange_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DownloadRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_exchange_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SecurityDefinition); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_exchange_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExecutionReport); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_exchange_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SessionReject); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_exchange_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*InMessage_Login)(nil),
		(*InMessage_Create)(nil),
		(*InMessage_Modify)(nil),
		(*InMessage_Cancel)(nil),
		(*InMessage_Massquote)(nil),
		(*InMessage_Secdefreq)(nil),
		(*InMessage_Download)(nil),
	}
	file_exchange_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*OutMessage_Login)(nil),
		(*OutMessage_Execrpt)(nil),
		(*OutMessage_Secdef)(nil),
		(*OutMessage_Reject)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_exchange_proto_rawDesc,
			NumEnums:      4,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_exchange_proto_goTypes,
		DependencyIndexes: file_exchange_proto_depIdxs,
		EnumInfos:         file_exchange_proto_enumTypes,
		MessageInfos:      file_exchange_proto_msgTypes,
	}.Build()
	File_exchange_proto = out.File
	file_exchange_proto_rawDesc = nil
	file_exchange_proto_goTypes = nil
	file_exchange_proto_depIdxs = nil
}
